USE DATABASE SURVEY_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE WAREHOUSE IF NOT EXISTS survey_agg_wh WITH WAREHOUSE_SIZE = 'XSMALL';

CREATE OR REPLACE TASK daily_gold_refresh
  WAREHOUSE = survey_agg_wh
  SCHEDULE = 'USING CRON 0 2 * * * UTC'
AS
  ALTER DYNAMIC TABLE agg_geo_sector_brand REFRESH;

ALTER TASK daily_gold_refresh RESUME;
