name: CD Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install SnowCLI
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-cli
      - name: Decode private key
        run: |
          printf "%s" "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" | base64 --decode > ${{ runner.temp }}/snowflake_key.pem
      - name: Deploy to production
        run: |
          snow sql -x --account "$SNOWFLAKE_ACCOUNT" --username "$SNOWFLAKE_USER" --role "$SNOWFLAKE_ROLE" --warehouse "$SNOWFLAKE_WAREHOUSE" --database "IMPRESSIONS_DB" --authenticator SNOWFLAKE_JWT --private-key-path "${{ runner.temp }}/snowflake_key.pem" --filename deploy.sql
